### ISSUE TITLE
Printing of the value type?

### ISSUE THREAD

**Issue by 0atman** [inim-repl/INim#62]
Like some shells can do:

```python
>>> 123
123 == type 'int'
```

Maybe using https://nim-lang.org/docs/typetraits.html

**Comment by 0atman** [comment]
or maybe using https://github.com/status-im/nim-stew/blob/master/stew/objects.nim#L37

**Comment by Yardanico** [comment]
Just use ``$typeof(value)`` to get a string for a type of a value

**Comment by 0atman** [comment]
Fixed in https://github.com/inim-repl/INim/pull/53

**Comment by Yardanico** [comment]
@0atman fixed? I think it's still not, since this issue is about printing the *type*

**Comment by 0atman** [comment]
```
👑 INim 0.4.7
Nim Compiler Version 1.2.0 [Linux: amd64] at /home/oatman/.nimble/bin/nim
nim> "hello world"
hello world == type string
nim> 

Quitting INim: Goodbye!
```
:ok_hand:
